[theme]
primaryColor = "#fa8f56"  # Vibrant OrangeRed
backgroundColor = "#121212"  # Darker background
secondaryBackgroundColor = "#1E1E1E"  # Slightly lighter dark grey
textColor = "#FAF3E1"  # Light grey for readability
font = "sans serif"  # Clean and modern font
